name: X86_64 AVX Normalization Benchmark

on:
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run Normalization Benchmark
        env:
          RUSTFLAGS: "-C target-cpu=native"
        run: |
          make bench-norm
